# Generated by Django 3.1 on 2020-08-29 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('address', models.CharField(max_length=250)),
                ('client_id', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Clients',
            },
        ),
    ]
